# Generated by Django 5.1.4 on 2025-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoWebapp', '0002_chatgptprompts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgptprompts',
            name='aiModel',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
